version: "3.9"

services:
  app:
    build: .
    command: uwsgi --ini config/uwsgi.ini
    volumes:
      - ./:/elearn/
    environment:
      - DJANGO_SETTINGS_MODULE=elearn.settings.prod
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=elearn
      - POSTGRES_USER=elearn
      - POSTGRES_PASSWORD=example

  redis:
    image: redis

volumes:
  postgres_data:

