version: "3.9"

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/elearn/
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=elearn.settings.local
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=elearn
      - POSTGRES_USER=elearn
      - POSTGRES_PASSWORD=example

  redis:
    image: redis

volumes:
  postgres_data:

